setwd('C:\\Users\\padmini\\Desktop\\exdata_data_household_power_consumption')
Consumption <- read.table( "household_power_consumption.txt",header=T, sep=";")
powerConsumption <-Consumption[as.character(Consumption$Date) %in% c("1/2/2007", "2/2/2007"),]
powerConsumption$dateTime = paste(powerConsumption2$Date, powerConsumption2$Time)
powerConsumption$dateTime <- strptime(powerConsumption$dateTime, "%d/%m/%Y %H:%M:%S")
attach(powerConsumption)
png("plot3.png", width=480, height=480, units="px")
plot(dateTime, as.numeric(as.character(Sub_metering_1)), type="l", xlab="", ylab="Energy sub metering", ylim=c(0,40))
lines(dateTime, as.numeric(as.character(Sub_metering_2)), col="red")
lines(dateTime, as.numeric(as.character(Sub_metering_3)), col="blue")
legend("topright", lty=1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3" ))
dev.off()
